{
 "title": "CORP - Redes Linx",
 "description": "Displays metrics collected by the host Zabbix Server",
 "tags": [ "Corporativo" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "base", "query": "Suporte_Grupo/Grupo-Soma.*" },
   {
    "name": "Grupo",
    "label": "Grupo",
    "query": "HG000000000038/AM/Manaus/Rede, HG000000000038/MG/Belo Horizonte/Rede, HG000000000038/MG/Uberlandia/Rede, HG000000000038/PE/Recife/Rede, HG000000000038/PR/Cascavel/Rede, HG000000000038/RJ/Rio de Janeiro/Rede, HG000000000038/RS/Porto Alegre/Rede, HG000000000038/SC/Blumenau/Rede, HG000000000038/SC/Florianopolis/Rede, HG000000000038/SC/Joinvile/Rede, HG000000000038/SP/Bauru/Rede, HG000000000038/SP/Bebedouro/Rede, HG000000000038/SP/Campinas/Rede, HG000000000038/SP/Matriz/Rede, HG000000000038/SP/Pinheiros/Rede"
   },
   { "name": "host", "label": "Devices", "query": "$Grupo.*" },
   { "name": "Interface", "label": "Interface - Incoming", "query": "$Grupo.$host.Interfaces.*" },
   { "name": "Interface2", "label": "Interface - Outgoing", "query": "$Grupo.$host.Interfaces.*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n\n<div style=\"width: 100%; height: 100%;\">\n<img src=\"http://ri.linx.com.br/wp-content/themes/mziq_linx/img/timeline/2015/img-linx.png\" align=\"left\"  height=\"70px\" wieght=\"50px\" /> \n<span style=\"font-size: 28px; padding-left:10px;\" >\n  <b>Corp. Redes</b></spam>\n\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 3 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Alarmes Ativos</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 7, "y": 3 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Alarmes em Tratativa</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 3 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Status do Link de Internet</b></spam></center>\n</div>"
  },
  {
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
   "targets": {
    "0": {},
    "Coletores Linx": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "Conec_Zabbix": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "WebMonitorPRD": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 5 },
   "targets": {
    "0": {},
    "Coletores Linx": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Suporte_Grupo" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "INFRAESTRUCTURE:Conectividade" },
     "trigger": { "filter": "" }
    },
    "Conec_Zabbix": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/Suporte_Grupo/Grupo-Soma.*/" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "WebMonitorPRD": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "type": "table",
   "description": "Status 1 = ok\nStatus 0 = Falha",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(: ICMP.*)/",
        " "
       ],
       "text": "replaceAlias(/(: ICMP.*)/,  )"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(Kinoplex - )/",
        " "
       ],
       "text": "replaceAlias(/(Kinoplex - )/,  )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/Link/" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 11 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 20px\" >\n  <b>Mapa dos Links</b></spam></center>\n</div>"
  },
  {
   "title": "Perda de Pacotes - Link",
   "type": "table",
   "description": "Verificado através do percentual de perda de pacotes do ICMP com o Coletor da Filial.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(: ICMP.*)/",
        " "
       ],
       "text": "replaceAlias(/(: ICMP.*)/,  )"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(Kinoplex - )/",
        " "
       ],
       "text": "replaceAlias(/(Kinoplex - )/,  )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/Link/" },
     "item": { "filter": "ICMP Perda Pacotes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 13 },
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT h.name as 'host', AVG(hist.value) as 'metric', inv.location_lat as 'latitude', inv.location_lon as 'longitude'\n\tFROM items i, hosts h, host_inventory inv, history hist\n\tWHERE i.name='ICMP Tempo de Resposta' AND h.name LIKE 'Link%' AND i.itemid=hist.itemid AND i.hostid=h.hostid AND inv.hostid=h.hostid AND h.status=0 and $__unixEpochFilter(hist.clock)\n\tGROUP BY 1,3,4\n\tORDER BY 'Host' DESC\n\tLIMIT 100;",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT h.name as 'host', COUNT(t.triggerid) as 'metric', inv.location_lat as 'latitude', inv.location_lon as 'longitude'\r\n\tFROM triggers t, functions f, items i, hosts h, host_inventory inv\r\n\tWHERE value = 1 AND t.triggerid=f.triggerid AND h.name LIKE 'Link%' AND i.itemid=f.itemid AND inv.hostid=h.hostid AND h.hostid=i.hostid AND h.status=0 AND t.status=0\r\n\tGROUP BY 1,3,4\r\n\tORDER BY 'Active Triggers' DESC\r\n\tLIMIT 100;",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 18 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Métricas de Interfaces</b></spam></center>\n</div>"
  },
  {
   "title": "Gráfico de Evolução Interface - Incoming Selecionada Hoje e Ontem",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 20 },
   "yaxes": [
    { "format": "decbytes", "label": "Uso da Interface" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "$Interface" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "$Interface" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming traffic on interface - Todas as Portas",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 25 },
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "/IN/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing traffic on interface - Todas as Portas",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 25 },
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Out/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gráfico de Evolução Interface - Outgoing Selecionada Hoje e Ontem",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 31 },
   "yaxes": [
    { "format": "decbytes", "label": "Uso da Interface" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "$Interface2" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "$Interface2" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU do Device Selecionado",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 36 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "System CPU Usage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memoria do Device Selecionado",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 36 },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(Usage)/",
        " "
       ],
       "text": "replaceAlias(/(Usage)/,  )"
      }
     ],
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "System Memory Usage(%)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}