{
 "title": "PRODUTOS - Microvix",
 "tags": [ "Microvix" ],
 "time": { "from": "2019-01-22T12:40:59.902Z", "to": "2019-01-22T13:40:59.902Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "content": "<div>\n<p>\n<img src=\"http://ri.linx.com.br/wp-content/themes/mziq_linx/img/timeline/2015/img-linx.png\" align=\"left\"  height=\"50px\" wieght=\"50px\" /> <h3> <b>Microvix</b></h3></p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 2, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>DTEF - Transação Financeira</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 8, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>MIDe - Emissão de Cupom Fiscal</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>GMUD - Pré-Execução</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>GMUD - Em Execução</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Disponibilidade</b></span>\n</div>"
  },
  {
   "title": "Quant. Última Hora",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Qtd1h Microvix" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Últimos 5min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink REDE" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_total_TML_REDE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Últimos 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "TempoMsLink REDE" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_total_TML_REDE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quant. Última Hora",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_ContadorMODA_microvix" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Últimos 5min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Tempo-5min-POSTOS_MICROVIX" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Últimos 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MID_tempos_Produtos" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Tempo-60min-POSTOS_MICROVIX" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "São analisadas as Pre execuções do Dia atual.",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT COUNT(*)\nFROM TRACEGP_HML_DEM_RDM\nWHERE ESTADO_DESCR = 'Pré Execução' and VERTICAL_PRODUTO like '%Microvix%' and DATA_INICIO_EXECUCAO = GETDATE()",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Que estão com Status em Execução.",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT COUNT(*)\nFROM TRACEGP_HML_DEM_RDM\nWHERE ESTADO_DESCR = 'Em Execução' and VERTICAL_PRODUTO like '%Microvix%'",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Últimas 24 horas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "MICROVIX",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Últimos 7 Dias",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "MICROVIX",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Últimos 30 Dias",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "MICROVIX",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 14px\"><b>Tempo de Autenticação POS</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 2, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Quantidade de Sincronizações POS por Minuto</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "content": "\n\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Sincronizações POS</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Melhor Sincronização POS | Pior Sincronização POS</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Home page" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "pos.microvix.com.br" },
     "item": { "filter": "/Response time for step*./" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "hoje" ],
       "text": "setAlias(hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "total_sinc_pos" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL_Microvix" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "total_sinc_pos" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Sincronização POS COM Sucesso",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "total_sinc_pos" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Sincronização POS SEM     Sucesso",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "total_sinc_sem_sucesso" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Medio Sincronização POS",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "tempo_medio_pos" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "tempo_minimo_pos_min_loja" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Melhor Tempo Sincronização",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "tempo_minimo_pos" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "tempo_maximo_pos_max_loja" },
     "itemids": "2184018",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Pior Tempo Sincronização",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "tempo_maximo_pos" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
   "content": "\n\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 14px\"><b>Tempo de Autenticação ERP</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 2, "y": 14 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Quantidade de Logins no ERP - Ativos Simultâneos</b></span>\n</div>"
  },
  {
   "title": "Top 5 Mais Lentos",
   "type": "table",
   "gridPos": { "h": 10, "w": 2, "x": 14, "y": 14 },
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "avg"
       ],
       "text": "top(5, avg)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)-MICROVIX: Performance(.*)/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)-MICROVIX: Performance(.*)/, $1)"
      }
     ],
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "/MCX PROD*/" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Status dos Bancos</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 16 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "microvix web" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "erp.microvix.com.br" },
     "item": { "filter": "Soma tempos de resposta Chrome" },
     "itemids": "917847",
     "mode": 3,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 2, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "hoje" ],
       "text": "setAlias(hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "total_erp_login" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SQL_Microvix" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "total_erp_login" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 16 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>DBs Não Homolog</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas - MICROVIX" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_DBsNaoHomolog" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 16 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Jobs Err</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas - MICROVIX" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_JobsErr" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 18 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>DBs OffLine</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "description": "Bases OffLine",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas - MICROVIX" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_DBsOffLine" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 18 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Falha de Backup</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas - MICROVIX" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_BackupErr" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 20 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Falha Login</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "description": "Sendo avaliado para definir valor de atuação.",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas - MICROVIX" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_FalhaLogin" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 20 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>End Of Support</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas - MICROVIX" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_EndOfSupport" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 22 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Total de Bases</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "description": "Informativo sobre o total de bases",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas - MICROVIX" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_DBsTotal" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 22 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Ultimo SP</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "description": "VMs com SP a ser instalado",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas - MICROVIX" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_UltimoSP" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 24 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Autenticação</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 24 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Transacionais</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 24 },
   "content": "\n\n\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Integração</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Jobs com Erros - Autenticação</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_JobsErr_Autenticacao" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 26 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Jobs com Erros nos Sevidores Transacionais</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_JobsErr_Transacional" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 26 },
   "content": "\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Jobs com Erros - Integração</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "cloudkpi-server" },
     "item": { "filter": "Microvix_JobsErr_Integracao" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 29 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Uso de CPU%</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 29 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Memoria em Uso%</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 29 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>SQL Server - Status</b></span>\n</div>"
  },
  {
   "title": "PROD 01-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 6, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 01-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 02-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 9, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 02-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 03-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 12, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 03-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 04-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 15, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 04-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 29 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>OpenVPN Access</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Startup {#SERVICE STARTUPNAME} services"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "MVXINT09  - Azure" },
     "item": {
      "filter": "State of service \"OpenVPNAccessClient\" (OpenVPN Access Client)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD - Azure" },
     "item": { "filter": "Total de uso de CPU em %" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD - Azure" },
     "item": { "filter": "Memória em uso %" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD - Azure" },
     "item": {
      "filter": "SQL Instance PROD: Service State - SQL Server"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 05-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 6, "y": 31.5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 05-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 06-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 9, "y": 31.5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 06-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 07-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 12, "y": 31.5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 07-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 08-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 15, "y": 31.5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 08-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 32 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>SQL Server - MVXINT09</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 32 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>SQL Server - MVXINT05</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 34 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Rede - Outgoing</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 34 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>Rede - Incoming</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 34 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>SQL Agent - Status</b></span>\n</div>"
  },
  {
   "title": "PROD 09-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 6, "y": 34 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 09-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 15-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 9, "y": 34 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 10-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 16-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 12, "y": 34 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 11-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 17-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 15, "y": 34 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 12-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "MVXINT09  - Azure" },
     "item": {
      "filter": "SQL Default Instance: Service State - SQL Server"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "MVXINT05  - Azure" },
     "item": {
      "filter": "SQL Default Instance: Service State - SQL Server"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 36 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD - Azure" },
     "item": {
      "filter": "Outgoing network traffic on Mellanox ConnectX-3 Virtual Function Ethernet Adapter #6"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 36 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD - Azure" },
     "item": {
      "filter": "Incoming network traffic on Mellanox ConnectX-3 Virtual Function Ethernet Adapter #6"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD - Azure" },
     "item": {
      "filter": "SQL Instance PROD: Service State - SQL Agent"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 36 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>SQL Agent - MVXINT09</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 36 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>SQL Agent - MVXINT05</b></span>\n</div>"
  },
  {
   "title": "PROD 18-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 6, "y": 36.5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 13-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 19-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 2.5, "w": 3, "x": 9, "y": 36.5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 14-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "MVXINT09  - Azure" },
     "item": {
      "filter": "SQL Default Instance: Service State - SQL Agent"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "MVXINT05  - Azure" },
     "item": {
      "filter": "SQL Default Instance: Service State - SQL Agent"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}