{
 "title": "PRODUTOS: DTEF",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "<div>\n<p>\n<div style=\"width: 100%; height: 100%; text-align: center;\">\n<span style=\"font-size: 22px; color: #FFFFFF; \"><img src=\"http://ri.linx.com.br/wp-content/themes/mziq_linx/img/timeline/2015/img-linx.png\" align=\"left\"  height=\"70px\" /></span></div>\n\n\n<center><span style=\"font-size: 42px\" >\n  <b>Dtef</b></spam></center>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Lojas Ativas</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Vendas Aprovadas 5min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Vendas Negadas</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Timeout  Finan</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Percentual Timeout</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Timeout N Finan</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Linx</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>ADQ</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "DTef por Base de Dados" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "HG000000000038/Produtos/TEF" },
     "host": { "filter": "Coletas DTef" },
     "item": { "filter": "/: LA/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "DTef por Base de Dados" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Coletas DTef" },
     "item": { "filter": "/: VA/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Negadas" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "/Vendas_Negada_*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeOut - Adq" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TIMEOUT_Todos" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeoutFinanceiro" },
     "group": { "filter": "HG000000000038/Produtos/TEF" },
     "host": { "filter": "Coletas DTef" },
     "item": {
      "filter": "Total Timeout Financeiro Porcentagem"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeoutNaoFinanceiro" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": {
      "filter": "NOC_DTEF_QtdeTimeoutNFinanceiro_Total"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Soma Tempo Linx" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_pacote_Linx5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink REDE" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_total_TML_REDE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 9 },
   "content": "<div style=\"width: 100%; text-align: center; padding-top: 30px;\">\n<span style=\"font-size: 32px\"><b>TEF </br>Ativo</b></span>\n</div>"
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 9 },
   "targets": [
    {
     "application": { "filter": "DTef por Base de Dados" },
     "group": { "filter": "HG000000000038/Produtos/TEF" },
     "host": { "filter": "Coletas DTef" },
     "item": { "filter": "/: TA/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 9 },
   "content": "<div style=\"width: 100%; text-align: center; padding-top: 30px;\">\n<span style=\"font-size: 32px\"><b>Reboot </br>Diario</b></span>\n</div>"
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "targets": [
    {
     "application": { "filter": "DTef por Base de Dados" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "6",
        "avg"
       ],
       "text": "top(6, avg)"
      }
     ],
     "group": { "filter": "HG000000000038/Produtos/TEF" },
     "host": { "filter": "Coletas DTef" },
     "item": { "filter": "/: RD/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Consolidado Vendas",
   "type": "graph",
   "description": "Consolidado agrupado em 15 minutos.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "DTef por Base de Dados" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vendas Aprovadas" ],
       "text": "setAlias(Vendas Aprovadas)"
      },
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "avg"
       ],
       "text": "groupBy(15m, avg)"
      }
     ],
     "group": { "filter": "HG000000000038/Produtos/TEF" },
     "host": { "filter": "Coletas DTef" },
     "item": { "filter": "/: VA/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "TimeoutFinanceiro" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Timeout Financeiro" ],
       "text": "setAlias(Timeout Financeiro)"
      },
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "avg"
       ],
       "text": "groupBy(15m, avg)"
      }
     ],
     "group": { "filter": "HG000000000038/Produtos/TEF" },
     "host": { "filter": "Coletas DTef" },
     "item": {
      "filter": "NOC_DTEF_QtdeTimeoutFinanceiro_Total"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "TimeoutNaoFinanceiro" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Timeout Não Finan" ],
       "text": "setAlias(Timeout Não Finan)"
      },
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "avg"
       ],
       "text": "groupBy(15m, avg)"
      }
     ],
     "group": { "filter": "HG000000000038/Produtos/TEF" },
     "host": { "filter": "Coletas DTef" },
     "item": {
      "filter": "NOC_DTEF_QtdeTimeoutNFinanceiro_Total"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Vendas Negadas" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vendas Negadas" ],
       "text": "setAlias(Vendas Negadas)"
      },
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "avg"
       ],
       "text": "groupBy(15m, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "/Vendas_Negada_*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Adquirentes</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 16 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Transação 1h</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 16 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Tempo 1h</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 16 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Tempo 5min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 16 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Timeout 5min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 16 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>% Timeout 5min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 14, "y": 16 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Evolução das Vendas</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 16 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 26px\"><b>Últimos 5min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "content": "<div style=\"padding-top: 20px;\">\n<p align=\"middle\"> <img src=\"https://noclinx.webmonitor.global/public/img/cielo.png\" align=\"middle\" align=\"top\" height=\"90px\"/>\n</div>\n</p>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "QtdeTransacoes x Adquirente CIELO"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_60min_QTA_CIELO" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 18 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink CIELO" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_60min TML CIELO" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 18 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink CIELO" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_10min_TML_CIELO" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeOut - Adq" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TIMEOUT_Cielo" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Percentual_TimeOut" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Percent_timeout_Cielo" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Transações Cielo",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Aprovadas Cielo" ],
       "text": "setAlias(Aprovadas Cielo)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Cielo" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Vendas Negadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vendas Negadas Cielo" ],
       "text": "setAlias(Vendas Negadas Cielo)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Cielo" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Aprovada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Cielo" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Negada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Negadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Cielo" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "content": "<div style=\"padding-top: 20px;\">\n<p align=\"middle\"> <img src=\"https://noclinx.webmonitor.global/public/img/redecard.png\" align=\"middle\" align=\"top\" height=\"90px\"/>\n</div>\n</p>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "QtdeTransacoes x Adquirente REDE"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_60min_QTA_REDE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink REDE" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_60min_TML_REDE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink REDE" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_5min_TML_REDE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeOut - Adq" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TIMEOUT_Rede" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Percentual_TimeOut" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Percent_timeout_Rede" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Transações Rede",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Aprovadas REDE" ],
       "text": "setAlias(Aprovadas REDE)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Rede" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Vendas Negadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vendas Negadas Rede" ],
       "text": "setAlias(Vendas Negadas Rede)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Rede" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Aprovada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Rede" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Negada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Negadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Rede" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "content": "<div style=\"padding-top: 20px\">\n<p align=\"middle\"> <img src=\"https://noclinx.webmonitor.global/public/img/getnet.png\" align=\"middle\" align=\"top\" height=\"100px\"/>\n</div>\n</p>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "QtdeTransacoes x Adquirente GetNet"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_60min_QTA_GetNet" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 26 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink GetNet" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_60min_TML_GetNet" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 26 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink GetNet" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_10min_TML_GetNet" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeOut - Adq" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TIMEOUT_Getnet" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Percentual_TimeOut" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Percent_timeout_Getnet" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Transações Getnet",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Aprovadas REDE" ],
       "text": "setAlias(Aprovadas REDE)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_GetNet" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Vendas Negadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vendas Negadas Rede" ],
       "text": "setAlias(Vendas Negadas Rede)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_GetNet" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Aprovada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_GetNet" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Negada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Negadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_GetNet" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "content": "<div style=\"padding-top: 20px;\">\n<p align=\"middle\"> <img src=\"https://raw.githubusercontent.com/nocoperadores/imgnoc/master/bin_black.png\" align=\"middle\" align=\"top\" height=\"90px\"/>\n</div>\n</p>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Transacoes - ADQ" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Transacoes_BIN" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 30 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Adquirente_BIN" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TempoMsLink_BIN_1h" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 30 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Adquirente_BIN" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TempoMsLink_BIN_5m" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeOut - Adq" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TIMEOUT_BIN" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 30 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Percentual_TimeOut" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Percent_timeout_BIN" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Transações BIN",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Aprovadas REDE" ],
       "text": "setAlias(Aprovadas REDE)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_BIN" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Vendas Negadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vendas Negadas Rede" ],
       "text": "setAlias(Vendas Negadas Rede)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_BIN" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Aprovada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_BIN" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Negada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Negadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_BIN" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "content": "<div style=\"padding-top: 20px;\">\n<p align=\"middle\"> <img src=\"https://raw.githubusercontent.com/nocoperadores/imgnoc/master/stone_black.png\" align=\"middle\" align=\"top\" height=\"100px\"/>\n</div>\n</p>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Transacoes - ADQ" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Transacoes_Stone" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 34 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Adquirente_Stone" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TempoMsLink_Stone_1h" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 34 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Adquirente_Stone" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TempoMsLink_Stone_5m" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeOut - Adq" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TIMEOUT_Stone" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 34 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Percentual_TimeOut" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Percent_timeout_Stone" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Transações Stone",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Aprovadas REDE" ],
       "text": "setAlias(Aprovadas REDE)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Stone" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Vendas Negadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vendas Negadas Rede" ],
       "text": "setAlias(Vendas Negadas Rede)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Stone" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Aprovada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Stone" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Negada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Negadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Stone" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "content": "<div style=\"padding-top: 20px;\">\n<p align=\"middle\"> <img src=\"https://raw.githubusercontent.com/nocoperadores/imgnoc/master/vero_black.png\" align=\"middle\" align=\"top\" height=\"100px\"/>\n</div>\n</p>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Transacoes - ADQ" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Transacoes_Vero" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 38 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Adquirente_VERO" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TempoMsLink_Vero_1h" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 38 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink Outros" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_60min_TML_Outros" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeOut - Adq" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TIMEOUT_Vero" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 38 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Percentual_TimeOut" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Percent_timeout_Vero" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Transações Vero",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Aprovadas REDE" ],
       "text": "setAlias(Aprovadas REDE)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Vero" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Vendas Negadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vendas Negadas Rede" ],
       "text": "setAlias(Vendas Negadas Rede)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Vero" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Aprovada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Vero" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Negada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Negadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Vero" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "content": "<div style=\"padding-top: 20px;\">\n<p align=\"middle\"> <img src=\"https://raw.githubusercontent.com/nocoperadores/imgnoc/master/Pay_hub.png\" align=\"middle\" align=\"top\" height=\"95px\"/>\n</div>\n</p>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Transacoes - ADQ" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Transacoes_LinxPay" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 42 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Adquirente_Stone" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TempoMsLink_Linx_Pay_Hub_1h" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 42 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Adquirente_Stone" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TempoMsLink_Linx_Pay_Hub_5m" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeOut - Adq" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TIMEOUT_Linx_Pay_Hub" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Percentual_TimeOut" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Percent_timeout_Linx_pay_Hub" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Transações Pay Hub",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Aprovadas Pay Hub" ],
       "text": "setAlias(Aprovadas Pay Hub)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Linx_Pay_Hub" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Vendas Negadas" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vendas Negadas Pay Hub" ],
       "text": "setAlias(Vendas Negadas Pay Hub)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Linx_Pay_Hub" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Aprovada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Linx_Pay_Hub" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Negada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 44 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Negadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Linx_Pay_Hub" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 },
   "content": "<div style=\"width: 100%; text-align: center; padding-top: 30px;\">\n<span style=\"font-size: 32px\"><b>Outros Adquirentes</b></span>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "QtdeTransacoes x Adquirente Outros"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_60min_QTA_Outros" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 46 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Adquirente_VERO" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TempoMsLink_Vero_5m" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 46 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink Outros" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_10min_TML_Outros" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TimeOut - Adq" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "TIMEOUT_Outros" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 46 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Percentual_TimeOut" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Percent_timeout_Outros" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Transações Outros",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": {
      "filter": "QtdeTransacoes x Adquirente Outros"
     },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Aprovadas REDE" ],
       "text": "setAlias(Aprovadas REDE)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_em_5min_QTA_Outros" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Negado_outros" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vendas Negadas Rede" ],
       "text": "setAlias(Vendas Negadas Rede)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Outros" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Aprovada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Vendas Aprovadas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_APROVADAS_Outros" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Negada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 48 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Negado_outros" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Vendas_Negada_Outros" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}