{
 "title": "PRODUTOS-Degust",
 "tags": [ "Degust" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "content": "<div style=\" padding-right: 20px;\">\n\n<img src=\"http://ri.linx.com.br/wp-content/themes/mziq_linx/img/timeline/2015/img-linx.png\" align=\"left\"  height=\"70px\" wieght=\"70px\" />\n</div>\n<div style=\"width: 100%; padding-top: 80px; padding-left: 20px;  text-align: left; font-size: 26px; \">\n  <b>Degust </b>\n</div>\n\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 20px\"><b>DTEF</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 20px\"><b>MIDe - Emissão Cupom</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>GMUD - Pré-Execução</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px\"><b>GMUD - Em Execução</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 20px\"><b>Usuarios Logado</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 20px\"><b>Flash de vendas</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 20px\"><b>Envio Movimento</b></span>\n</div>"
  },
  {
   "title": "Quant. Últimos 5min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Dtef_festivas" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Qtd5min_Degust" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Últimos 5min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink REDE" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_total_TML_REDE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quant. Últimos 5min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorFOODSERVICE_nfcedb_5min"
     },
     "itemids": "2205391",
     "mode": 3,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Últimos 5min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID_tempos_Produtos" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Tempo-5min-FOOD_Degust" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "São analisadas as Pre execuções do Dia atual.",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT COUNT(*)\nFROM TRACEGP_HML_DEM_RDM\nWHERE ESTADO_DESCR = 'Pré Execução' and VERTICAL_PRODUTO like '%Degust%'and DATA_INICIO_EXECUCAO = GETDATE()",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Que estão com Status em Execução.",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT COUNT(*)\nFROM TRACEGP_HML_DEM_RDM\nWHERE ESTADO_DESCR = 'Em Execução' and VERTICAL_PRODUTO like '%Degust%'",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "TotalLogins_TUDO" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "TotalCupons_TUDO" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "RecebtoMovto_TOTAL" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 } },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 }, "content": "Link" },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 2, "y": 7 },
   "content": "\n<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 20px\"><b>Status do Comunicador</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "content": "\n<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 16px\"><b>Usuarios Logado</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 7 },
   "content": "\n<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 16px\"><b>Flash de vendas</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
   "content": "\n<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 16px\"><b>Envio Movimento</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "content": "\n<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 20px\"><b>Tempo de Login</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "content": "\n<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<span style=\"font-size: 20px\"><b>Tempo Abertura Painel</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 10 },
   "content": "<div  style=\"width: 100%; text-align: center; padding-top:20px;\">\n<img src=\"https://raw.githubusercontent.com/nocoperadores/personal/master/linx_REDE_RESTAURANTES.png\">\n<!-- <h3 align=\"middle\">testo</h3> -->\n</div>"
  },
  {
   "title": "Sincronismo",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-148 - Azure" },
     "item": { "filter": "/DEGUST - Sincronismo*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Comunicador Server",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-148 - Azure" },
     "item": { "filter": "/DEGUST - ComunicadorServer*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Guardian",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-148 - Azure" },
     "item": {
      "filter": "/DEGUST - ComunicadorGuardian*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "URL",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Home page" },
     "group": { "filter": "/.*/" },
     "host": {
      "filter": "Monitoramento Web Producao - comunicador.degust.com.br"
     },
     "item": { "filter": "/Response code for step*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "quantidade_GERAL" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Home page" },
     "group": {
      "filter": "HG000000000038/Produtos/Degust/Portal"
     },
     "host": {
      "filter": "Monitoramento Web Producao - comunicador.degust.com.br"
     },
     "item": { "filter": "" },
     "itemids": "2208782",
     "mode": 3,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "RecebtoMovto_Geral" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "TEMPO_LOGIN_GERAL" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "carregarPainelLojas_GERAL" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 15 },
   "content": "<div  style=\"width: 100%; text-align: center; padding-top:20px;\">\n<img src=\"https://raw.githubusercontent.com/nocoperadores/personal/master/linx_RESTAURANTES_INDIV.png\">\n<!-- <h3 align=\"middle\">testo</h3> -->\n</div>"
  },
  {
   "title": "Sincronismo",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-139 - Azure" },
     "item": { "filter": "/DEGUST - Sincronismo*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Comunicador Server",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-139 - Azure" },
     "item": { "filter": "/DEGUST - ComunicadorServer*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Guardian",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-139 - Azure" },
     "item": {
      "filter": "/DEGUST - ComunicadorGuardian*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "URL",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Home page" },
     "group": { "filter": "/.*/" },
     "host": {
      "filter": "Monitoramento Web Varejo - comunicadorvarejo.degust.com.br"
     },
     "item": { "filter": "/Response code for step*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB03 - Azure" },
     "item": { "filter": "quantidade_VAREJO2" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB03 - Azure" },
     "item": { "filter": "TotalCupons_Varejo" },
     "itemids": "2208784",
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB03 - Azure" },
     "item": { "filter": "RecebtoMovto_Varejo" },
     "itemids": "2208783",
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB03 - Azure" },
     "item": { "filter": "TempoLogin_VAREJO" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB03 - Azure" },
     "item": { "filter": "carregarPainelLojas_VAREJO" },
     "itemids": "2209915",
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 20 },
   "content": "<div  style=\"width: 100%; text-align: center; padding-top:20px;\">\n<img src=\"https://raw.githubusercontent.com/nocoperadores/personal/master/giraffas_preto.png\">\n<!-- <h3 align=\"middle\">testo</h3> -->\n</div>"
  },
  {
   "title": "Sincronismo",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-313 - Azure" },
     "item": { "filter": "/DEGUST - Sincronismo*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Comunicador Server",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-313 - Azure" },
     "item": { "filter": "/DEGUST - ComunicadorServer*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Guardian",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-313 - Azure" },
     "item": {
      "filter": "/DEGUST - ComunicadorGuardian*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "URL",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Home page" },
     "group": { "filter": "/.*/" },
     "host": {
      "filter": "Monitoramento Web Giraffas - comunicadorgiraffas.degust.com.br"
     },
     "item": { "filter": "/Response code for step*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "quantidade_GIRAFFAS_LOG3" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "TotalCupons_Giraffas" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "RecebtoMovto_Giraffas" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "TEMPO_LOGIN_GIRAFFAS_LOG3" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": {
      "filter": "carregarPainelLojas_DEGUST_GIRAFFAS_LOG3"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 25 },
   "content": "<div  style=\"width: 100%; text-align: center; padding-top:20px;\">\n<img src=\"https://raw.githubusercontent.com/nocoperadores/personal/master/bobs_preto.png\">\n<!-- <h3 align=\"middle\">testo</h3> -->\n</div>"
  },
  {
   "title": "Sincronismo",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-151 - Azure" },
     "item": { "filter": "/DEGUST - Sincronismo*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Comunicador Server",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-151 - Azure" },
     "item": { "filter": "/DEGUST - ComunicadorServer*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Guardian",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Degust" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LS01-151 - Azure" },
     "item": {
      "filter": "/DEGUST - ComunicadorGuardian*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "URL",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Home page" },
     "group": { "filter": "/.*/" },
     "host": {
      "filter": "Monitoramento Web BFFC - comunicadorbffc.degust.com.br"
     },
     "item": { "filter": "/Response code for step*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB01 - Azure" },
     "item": { "filter": "Quantidade_BFFC4" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB01 - Azure" },
     "item": { "filter": "TotalCupons_Bobs" },
     "itemids": "2208780",
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB01 - Azure" },
     "item": { "filter": "RecebtoMovto_Bobs" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB01 - Azure" },
     "item": { "filter": "TempoLogin_BFFC" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB01 - Azure" },
     "item": { "filter": "carregarPainelLojas_BFFC" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 30 },
   "content": "<div  style=\"width: 100%; text-align: center; padding-top: 5px;\">\n<img src=\"https://raw.githubusercontent.com/nocoperadores/personal/master/hab_preto.png\" height=\"120px\" wieght=\"120px\" >\n<!-- <h3 align=\"middle\">testo</h3> -->\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 2, "y": 30 },
   "content": "\n<div style=\"width: 100%; text-align: center; padding-top: 55px;\">\n<span style=\"font-size: 20px\"><b>Infraestrutura - Cliente</b></span>\n</div>"
  },
  {
   "title": "URL",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Home page" },
     "group": { "filter": "/.*/" },
     "host": {
      "filter": "Monitoramento Web BFFC - comunicadorbffc.degust.com.br"
     },
     "item": { "filter": "/Response code for step*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "quantidade_Habibs" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "TotalCupons_HABIBS" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "RecebtoMovto_HABIBS" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": { "filter": "TEMPO_LOGIN_GERAL_Habibs" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Consulta Versao" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDGTDB02 - Azure" },
     "item": {
      "filter": "carregarPainelLojas_GERAL_Habibs_copy"
     },
     "itemids": "2210713",
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}