{
 "title": "CORP-Firewall_Internet",
 "tags": [ "Infraestrutura" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"width: 100%; height: 100%;\">\n<img src=\"http://ri.linx.com.br/wp-content/themes/mziq_linx/img/timeline/2015/img-linx.png\" align=\"left\"  height=\"70px\" wieght=\"50px\" /> \n\n<div style=\"padding: 10px\">\n<span style=\"font-size: 26px; color: #FFFFFF;\"><b>Firewall e Internet Corporativos</span>\n</div>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 3 },
   "content": "<div style=\"width: 100%; padding: 1px 0; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF;\"><b>SAAS TAMBORÉ</b> </span>\n</div> "
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 3 },
   "content": "<div style=\"width: 100%; padding: 1px 0; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF;\"><b>MATRIZ</b> </span>\n</div> "
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 5 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px; \"><b>Grafico de entrada Últimas 06 horas - SAAS</span>\n</div> "
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "content": "<div style=\"width: 100%; padding: 1px 0; text-align: center;\">\n<span style=\"font-size: 16px; color: #FFFFFF;\"><b>Download</b> </span>\n</div> "
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 12, "y": 5 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px; \"><b>Grafico de entrada Últimas 06 horas - MATRIZ</span>\n</div> "
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 5 },
   "content": "<div style=\"width: 100%; padding: 1px 0; text-align: center;\">\n<span style=\"font-size: 16px; color: #FFFFFF;\"><b>Download</b> </span>\n</div> "
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Consumo MB" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Link Embratel" ],
       "text": "setAlias(Link Embratel)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Incoming HC traffic on interface SW BORDA _ PORTs 09/10"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Link Diveo" ],
       "text": "setAlias(Link Diveo)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Incoming traffic on interface toUOLDiveo, porta xx switch xx, porta 999"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Diveo",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Incoming traffic on interface toUOLDiveo, porta xx switch xx, porta 999"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Consumo MB" }
   ],
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Link Vivo" ],
       "text": "setAlias(Link Vivo)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Incoming HC traffic on interface port5"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interface(s)" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Link Telium" ],
       "text": "setAlias(Link Telium)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Incoming HC traffic on interface port3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Telium",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Incoming HC traffic on interface port3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Diveo In. discarded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Incoming discarded packets on interface toUOLDiveo, porta xx switch xx, porta 999"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Telium In. discarded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Incoming discarded packets on interface port3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Embratel",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Incoming HC traffic on interface SW BORDA _ PORTs 09/10"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIVO",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Incoming HC traffic on interface port5"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Embratel In. discarded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Incoming discarded packets on interface SW BORDA _ PORTs 09/10"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIVO In. discarded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Incoming discarded packets on interface port5"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 15 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px; \"><b>Grafico de saída Últimas 06 horas - SAAS</span>\n</div> "
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 15 },
   "content": "<div style=\"width: 100%; padding: 1px 0; text-align: center;\">\n<span style=\"font-size: 16px; color: #FFFFFF;\"><b>Upload</b> </span>\n</div> "
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 12, "y": 15 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 20px; \"><b>Grafico de saída Últimas 06 horas - MATRIZ</span>\n</div> "
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 15 },
   "content": "<div style=\"width: 100%; padding: 1px 0; text-align: center;\">\n<span style=\"font-size: 16px; color: #FFFFFF;\"><b>Upload</b> </span>\n</div> "
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Consumo MB" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Link Embratel" ],
       "text": "setAlias(Link Embratel)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Outgoing HC traffic on interface SW BORDA _ PORTs 09/10"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Link Diveo" ],
       "text": "setAlias(Link Diveo)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Outgoing HC traffic on interface toUOLDiveo, porta xx switch xx, porta 999"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Diveo",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Outgoing HC traffic on interface toUOLDiveo, porta xx switch xx, porta 999"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Consumo MB" }
   ],
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Link Vivo" ],
       "text": "setAlias(Link Vivo)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Outgoing HC traffic on interface port5"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interface(s)" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Link Telium" ],
       "text": "setAlias(Link Telium)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Outgoing HC traffic on interface port3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Telium",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Outgoing HC traffic on interface port3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Diveo Out. discarded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Outgoing discarded packets on interface toUOLDiveo, porta xx switch xx, porta 999"
     },
     "itemids": "2237582",
     "mode": 3,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Telium Out. discarded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Outgoing discarded packets on interface port3"
     },
     "itemids": "864839",
     "mode": 3,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Embratel",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Outgoing HC traffic on interface SW BORDA _ PORTs 09/10"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIVO",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Outgoing HC traffic on interface port5"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Embratel Out. discarded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 23 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Outgoing discarded packets on interface SW BORDA _ PORTs 09/10"
     },
     "itemids": "2237585",
     "mode": 3,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIVO Out. discarded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 23 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Outgoing discarded packets on interface port5"
     },
     "itemids": "864841",
     "mode": 3,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 25 },
   "content": "<div style=\"width: 100%; padding: 1px 0; text-align: center;\">\n<span style=\"font-size: 24px; \"><b>CPU | Memória | Status FW SAAS TAMBORÉ</b> </span>\n</div> "
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 25 },
   "content": "<div style=\"width: 100%;  padding: 1px 0; text-align: center;\">\n<span style=\"font-size: 24px; \"><b>CPU | Memória | Status FW MATRIZ</b> </span>\n</div> "
  },
  {
   "title": "Gráfico Uso CPU em %",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": { "filter": "System CPU Usage" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": { "filter": "System CPU Usage" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 27 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 16px; color: #FFFFFF;\"><b>Status<br>Interface</b> </span>\n</div> "
  },
  {
   "title": "Diveo",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Operational status of interface toUOLDiveo, porta xx switch xx, porta 999"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Embratel",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": {
      "filter": "Operational status of interface SW BORDA _ PORTs 09/10"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gráfico Uso CPU em %",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": { "filter": "System CPU Usage" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": { "filter": "System CPU Usage" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 27 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 16px; color: #FFFFFF;\"><b>Status<br>Interface</b> </span>\n</div> "
  },
  {
   "title": "Telium",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Operational status of interface port3"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIVO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": {
      "filter": "Operational status of interface port5"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gráfico Uso Memória em %",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": { "filter": "System Memory Usage(%)" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso Memória",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 30 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": { "filter": "System Memory Usage(%)" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 30 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 16px; color: #FFFFFF;\"><b>Status<br>Geral</b> </span>\n</div> "
  },
  {
   "title": "ICMP Ping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP Perda Pacotes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 30 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Firewall Tambore Cloud" },
     "item": { "filter": "ICMP Perda Pacotes" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gráfico Uso Memória em %",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": { "filter": "System Memory Usage(%)" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso Memória",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 30 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": { "filter": "System Memory Usage(%)" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 30 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 16px; color: #FFFFFF;\"><b>Status<br>Geral</b> </span>\n</div> "
  },
  {
   "title": "ICMP Ping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP Perda Pacotes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 30 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "FW-DCM-001 - Matriz" },
     "item": { "filter": "ICMP Perda Pacotes" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}