{
 "title": "Alarmes-vertical",
 "description": "Displays metrics collected by the host Zabbix Server",
 "tags": [ "Neri" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "group", "label": "group", "query": "*" },
   { "name": "host", "label": "host", "query": "$group.*" },
   { "name": "aplication", "label": "Tipo Sensor", "query": "$group.$host.*" }
  ]
 },
 "panels": [
  {
   "title": "Alarmes",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": {
    "WebMonitorPRD": {
     "application": { "filter": "$aplication" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "title": "Total de uso de CPU em %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total de uso de CPU em %" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memória em uso %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória em uso %" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Disk space percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Free disk.*(percentage)/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used disk space on C:",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Used disk space on C:" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}