{
 "title": "CORP  - Balanceador",
 "tags": [ "Corporativo" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "content": "<div style=\"width: 100%; height: 100%;\">\n<img src=\"http://ri.linx.com.br/wp-content/themes/mziq_linx/img/timeline/2015/img-linx.png\" align=\"left\"  height=\"60px\" />\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 22, "x": 2, "y": 0 },
   "content": "<div style=\"width: 100%; height: 100%;\">\n  <center>\n<span style=\"font-size: 36px; color: #FFFFFF;\" >\n  <b>Balance A10</b></spam> </cemter>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 10px\">\n\n<center><span style=\"font-size: 20px\" >\n  <b>CPU em Uso</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 10px\">\n\n<center><span style=\"font-size: 20px\" >\n  <b>Memória em Uso</b></spam></center>\n</div>"
  },
  {
   "title": "Consumo IN - OUT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "bytes", "label": "Consumo IN - OUT" }
   ],
   "targets": [
    {
     "application": { "filter": "VIP_WORKFLOW" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": { "filter": "axVirtualServerStatBytesIn" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "VIP_WORKFLOW" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": { "filter": "axVirtualServerStatBytesOut" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Balanceamento VIP WorkFlow",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Quantidade de Conexões" }
   ],
   "targets": [
    {
     "application": { "filter": "SVC_WORKFLOW_A-SRV382" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "A-SRV382" ],
       "text": "setAlias(A-SRV382)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW_A-SRV382-axServiceGroupMemberStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SVC_WORKFLOW_A-SRV383" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "A-SRV383" ],
       "text": "setAlias(A-SRV383)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW_A-SRV383-axServiceGroupMemberStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": { "filter": "axSysAverageCpuUsage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": { "filter": "axSysMemoryUsage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 15px\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Endereço do VIP</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "VIP_WORKFLOW" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": { "filter": "axVirtualServerStatAddress" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Conexões VIP - WorkFlow",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Quantidade de Conexões" }
   ],
   "targets": [
    {
     "application": { "filter": "VIP_WORKFLOW" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": { "filter": "axVirtualServerStatCurConns" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "VIP_WORKFLOW" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": { "filter": "axVirtualServerStatCurConns" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 15px\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Conexões</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP_WORKFLOW" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": { "filter": "axVirtualServerStatCurConns" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Status VIPs</b></spam></center>\n</div>"
  },
  {
   "title": "VIP_WORKFLOW",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP_WORKFLOW" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "/.*axVirtualServerStatDisplayStatus/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIP-CORP-INT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP-CORP-INT" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "/.*axVirtualServerStatDisplayStatus/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIP-CORP-EXT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP-CORP-EXT" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "/.*axVirtualServerStatDisplayStatus/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIP-TS-Gateway",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP-TS-Gateway" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "/.*axVirtualServerStatDisplayStatus/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIP-SG-thanks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP-SG-thanks" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "/.*axVirtualServerStatDisplayStatus/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIP_WSFARMCORP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP_WSFARMCORP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "/.*axVirtualServerStatDisplayStatus/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIP-TS-RDS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP-TS-RDS" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "/.*axVirtualServerStatDisplayStatus/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIPLOOQBOX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIPLOOQBOX" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "/.*axVirtualServerStatDisplayStatus/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIP_CHECK_AWS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "VIP_HEALTH_CHECK_AWS_SVC_A-SRV2000"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "/.*axVirtualServerStatDisplayStatus/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VIP-TS-RDS-RM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP-TS-RDS-RM" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "/.*axVirtualServerStatDisplayStatus/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 5px\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Serviço do WorkFlow</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 15px\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Status</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 20 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 15px\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Conexões</b></spam></center>\n</div>"
  },
  {
   "title": "Conexões Serviço WorkFlow",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Quantidade de Conexões" }
   ],
   "targets": [
    {
     "application": { "filter": "SVC_WORKFLOW" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW-axServiceGroupStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SVC_WORKFLOW" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW-axServiceGroupStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP_WORKFLOW" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "axVirtualServerStatDisplayStatus"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SVC_WORKFLOW" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW-axServiceGroupStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 26 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>A-SRV382</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 26 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>A-SRV383</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 28 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 10px\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Status</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 28 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 10px\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Conexões</b></spam></center>\n</div>"
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Quantidade de Conexões" }
   ],
   "targets": [
    {
     "application": { "filter": "SVC_WORKFLOW_A-SRV382" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Conexões - Hoje" ],
       "text": "setAlias(Conexões - Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW_A-SRV382-axServiceGroupMemberStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SVC_WORKFLOW_A-SRV382" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Conexões - Ontem" ],
       "text": "setAlias(Conexões - Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW_A-SRV382-axServiceGroupMemberStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 28 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 10px\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Status</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 28 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center; padding-top: 10px\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Conexões</b></spam></center>\n</div>"
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Quantidade de Conexões" }
   ],
   "targets": [
    {
     "application": { "filter": "SVC_WORKFLOW_A-SRV383" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Conexões - Hoje" ],
       "text": "setAlias(Conexões - Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW_A-SRV383-axServiceGroupMemberStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "SVC_WORKFLOW_A-SRV383" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Conexões - Ontem" ],
       "text": "setAlias(Conexões - Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW_A-SRV383-axServiceGroupMemberStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP_WORKFLOW" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "axVirtualServerStatDisplayStatus"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SVC_WORKFLOW_A-SRV382" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW_A-SRV382-axServiceGroupMemberStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "VIP_WORKFLOW" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "axVirtualServerStatDisplayStatus"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SVC_WORKFLOW_A-SRV383" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Balance Matriz 01" },
     "item": {
      "filter": "SVC_WORKFLOW_A-SRV383-axServiceGroupMemberStatCurConns"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}