{
 "title": "CORP: Blade Chassis",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "group", "label": "group", "query": "*" },
   { "name": "host", "label": "Host", "query": "$group.*" },
   { "name": "application", "label": "Application", "query": "$group.$host.*" },
   { "name": "item", "label": "Item", "query": "$group.$host.$application.*" },
   { "name": "copy_of_host", "label": "Host", "query": "$group.*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 22px\"><b>Status Blade CMC-HB6BFP1</b></span>\n</div>"
  },
  {
   "title": "Overall System Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temprature Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "Overall Temprature Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Power Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC Power Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC Health Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temperatura CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 3 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC CPU Temprature" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temperatura Chassis",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 3 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "Chassis FrontPanel Temprature" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Voltagem de entrada",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "6",
        "avg"
       ],
       "text": "top(6, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": {
      "filter": "/Power Supply.*..Input Voltage/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "FAN Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "avg"
       ],
       "text": "groupBy(15m, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC Fan Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IOM Subsystem Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "avg"
       ],
       "text": "groupBy(15m, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "IOM Subsystem Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "iKVM  Health Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "iKVM Subsystem Health Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redundancy Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC Redundancy Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Consumo de Energia",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 8 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC System Energy Consumption" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "System Input Power",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 8 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC System Input Power" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ampere de entrada",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "6",
        "avg"
       ],
       "text": "top(6, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "/Power Supply.*.Input Amps/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 13 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 22px\"><b>Status System PowerEdgeM610</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 13 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 22px\"><b>Temperatura e Watts PowerEdgeM610</b></span>\n</div>"
  },
  {
   "title": "A-SRV351",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/SP/Matriz" },
     "host": { "filter": "A-SRV351" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV352",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/SP/Matriz" },
     "host": { "filter": "A-SRV352" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV353",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/SP/Matriz" },
     "host": { "filter": "A-SRV353" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV354",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/SP/Matriz" },
     "host": { "filter": "A-SRV354" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV364",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/Laminas" },
     "host": { "filter": "A-SRV364" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV362",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/Laminas" },
     "host": { "filter": "A-SRV362" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV360",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/Laminas" },
     "host": { "filter": "A-SRV360" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "application": { "filter": "Temperature" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "avg"
       ],
       "text": "top(5, avg)"
      }
     ],
     "group": { "filter": "HG000000000038/Laminas" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Temperature sensor" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV356",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/SP/Matriz" },
     "host": { "filter": "A-SRV356" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV355",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/SP/Matriz" },
     "host": { "filter": "A-SRV355" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV359",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/Laminas" },
     "host": { "filter": "A-SRV359" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV357",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "A-SRV357 - Hyper-V TraceGP" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "A-SRV361",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/Laminas" },
     "host": { "filter": "A-SRV361" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV358",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/Laminas" },
     "host": { "filter": "A-SRV358" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "A-SRV363",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/Laminas" },
     "host": { "filter": "A-SRV363" },
     "item": { "filter": "Overall System Status2" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Watts de entrada",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "application": { "filter": "System Level" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "avg"
       ],
       "text": "top(5, avg)"
      }
     ],
     "group": { "filter": "HG000000000038/Laminas" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "System Level" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Incidentes Ativos  PowerEdgeM610",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "targets": {
    "WebMonitorPRD": {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "title": "Incidentes Ativos CMC-HB6BFP1",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "targets": {
    "WebMonitorPRD": {
     "application": { "filter": "" },
     "group": { "filter": "HG000000000038/Laminas" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  }
 ]
}