{
 "title": "NovoMicrovix",
 "tags": [ "Microvix" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "content": "<div>\n<p>\n<img src=\"http://ri.linx.com.br/wp-content/themes/mziq_linx/img/timeline/2015/img-linx.png\" align=\"left\"  height=\"50px\" wieght=\"50px\" /> <h3> <b>Microvix</b></h3></p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "content": "<div  align=\"center\" >\n\n\n<p><h3>Disponibilidade </h3></p>\n\n</div>"
  },
  { "type": "text", "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Últimas 24 horas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "MICROVIX",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Últimos 7 Dias",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "MICROVIX",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Últimos 30 Dias",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "MICROVIX",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quantidade de Sincronizações POS por Minuto",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "total_sinc_pos" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Sincronização POS COM Sucesso",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "total_sinc_pos" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Sincronização POS SEM     Sucesso",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "total_sinc_sem_sucesso" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Medio Sincronização POS",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "tempo_medio_pos" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Melhor Sincronização POS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "tempo_minimo_pos_min_loja" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Melhor Tempo Sincronização",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "tempo_minimo_pos" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Pior Tempo Sincronização",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "tempo_maximo_pos" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Loja Pior Sincronização POS Loja",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "tempo_maximo_pos_max_loja" },
     "itemids": "2184018",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quantidade de Logins no ERP - Ativos Simultâneos",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "SQL_Microvix" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "SQLMVXWEBAUTPROD" },
     "item": { "filter": "total_erp_login" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo de Autenticação ERP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "microvix web" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "erp.microvix.com.br" },
     "item": { "filter": "Soma tempos de resposta Chrome" },
     "itemids": "917847",
     "mode": 3,
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo de Autenticação - POS",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Home page" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "pos.microvix.com.br" },
     "item": { "filter": "/Response time for step*./" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Top 5 Mais Lentos",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "avg"
       ],
       "text": "top(5, avg)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)-MICROVIX: Performance(.*)/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)-MICROVIX: Performance(.*)/, $1)"
      }
     ],
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "/MCX PROD*/" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 01-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 01-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 02-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 02-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 03-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 03-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 04-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 04-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 05-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 05-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 06-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 06-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 07-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 07-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 08-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 08-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 09-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 09-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 15-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 10-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 16-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 27 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 11-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 17-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 12-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 18-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 27 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 13-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PROD 19-MICROVIX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 27 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "MCX PROD 14-MICROVIX" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Dispersão ultimas 6 horas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "Microvix" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)-MICROVIX: Performance(.*)/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)-MICROVIX: Performance(.*)/, $1)"
      }
     ],
     "group": {
      "filter": "HG000000000038/Produtos/Microvix"
     },
     "host": { "filter": "/MCX PROD*/" },
     "item": { "filter": "Performance" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}