{
 "title": "PRODUTOS: MIDe - Desempenho de Emissoes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 24px; color: #4682B4; padding-right:150px\"><b>Desempenho das emissões</b> </span>\n<img src=\"https://uniredeinfo-my.sharepoint.com/personal/hernandes_martins_unirede_net/_layouts/15/guestaccess.aspx?docid=019add617d2da4d48b78a7d349e288209&authkey=ASLOqLFi9YyWYZxXWGNB4_o&e=12e79e2af650446b8d44ab81482a6c7b\" align=\"left\" align=\"top\" height=\"50px\" />\n\n\n </div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h2> \n<b>Vertical</b></h2></p>\n\n</div>\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 15px\"><b>Cupons  Emitidos<br>Últimos 60min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 15px\"><b>% Emissão Online<br>Últimos 60min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 15px\"><b>Tempo Médio de Emissão<br>Últimos 5min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 15px\"><b>Tempo Médio de Emissão<br>Últimos 60min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h3> \n<b>Localidade - Ambiente</b></h3></p>\n\n</div>\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 15px\"><b>Tempo Médio de Emissão<br>Últimos 5min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 15px\"><b>Tempo Médio de Emissão<br>Últimos 60min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 15px\"><b>Total Emitido<br>Últimos 60min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 15px\"><b>Contingência</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 15px\"><b>Acima de 2s</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 15px\"><b>Percentual Emitido<br>Últimos 60min</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n<h1> \n<b>MODA</b></h1></p></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_ContadorMODA_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_MODA_percent_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_MODA_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_MODA_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "content": "<div style=\"width: 100%; height: 100%;  padding-top:10px; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF; \"><b>Tamboré -  MIDe</b> </span></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "MID_central_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "MID_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MID_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "NFCEDB - Contingencia" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Contingencia_MIDCentral_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Acima_2s_MID_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "PercEmissaoServidor_60min_Central"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "content": "<div style=\"width: 100%; height: 100%; padding-top:10px; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF; \"><b>Tamboré - PDE Central - MIDe6</b> </span></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 9 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "MID6_central_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 9 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "MID6_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MID6_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "NFCEDB - Contingencia" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Contingencia_MID_mide6_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Acima_2s_MID6_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "PercEmissaoServidor_MIDe6_60min"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 10 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n<h1> \n<b>FOOD</b></h1></p></div>\n"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorFOODSERVICE_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_FOODSERVICE_Percent_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 10 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_FOOD_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 10 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_FOOD_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "content": "<div style=\"width: 100%; height: 100%;  padding-top:10px; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF; \"><b>Azure - PDE MIDe4</b> </span></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 12 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "MID4_central_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 12 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "MID4_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MID4_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "NFCEDB - Contingencia" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Contingencia_MID_azure_mide4_60min"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Acima_2s_MID4_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "PercEmissaoServidor_MIDe4_60min"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 14 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n<h1> \n<b>POSTOS</b></h1></p></div>\n"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_ContadorPOSTOS_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_POSTOS_percent_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 14 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_POSTOS_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 14 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_POSTOS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
   "content": "<div style=\"width: 100%; height: 100%;  padding-top:10px; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF; \"><b>Azure - PDE MIDe5</b> </span></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 15 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "MID5_central_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "MID5_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MID5_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "NFCEDB - Contingencia" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Contingencia_MID_azure_mide5_60min"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Acima_2s_MID5_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "PercEmissaoServidor_MIDe5_60min"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 18 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n<h1> \n<b>DMS</b></h1></p></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_ContadorDMS_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_DMS_percent_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_DMS_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_DMS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 18 },
   "content": "<div style=\"width: 100%; height: 100%;  padding-top:10px; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF; \"><b>Azure - PDE MIDe7</b> </span></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "MID7_central_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "MID7_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MID7_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Contingencia_MID_mid7_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Acima_2s_MID7_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "PercEmissaoServidor_MID7_1h" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 21 },
   "content": "<div style=\"width: 100%; height: 100%;  padding-top:10px; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF; \"><b>MIDevo</b> </span></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 21 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "mideevo_central_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 21 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "mideevo_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MIDevo_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Contingencia_MID_mideevo_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Acima_2s_mideevo_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "PercEmissaoServidor_mideevo_1h" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 22 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n<h1> \n<b>BIG RETAIL</b></h1></p></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorBIGRETAIL_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_BIGRETAIL_percent_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 22 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_BIGRETAIL_nova_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 22 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_BIGRETAIL_nova_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Curva de Emissão",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "max"
       ],
       "text": "top(10, max)"
      },
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "max"
       ],
       "text": "aggregateBy(15m, max)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Central" ],
       "text": "setAlias(Central)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MID_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "max"
       ],
       "text": "top(10, max)"
      },
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "max"
       ],
       "text": "aggregateBy(15m, max)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe-4 Azure" ],
       "text": "setAlias(MIDe-4 Azure)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MID4_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "max"
       ],
       "text": "top(10, max)"
      },
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "max"
       ],
       "text": "aggregateBy(15m, max)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe-5 Azure" ],
       "text": "setAlias(MIDe-5 Azure)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MID5_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "max"
       ],
       "text": "top(10, max)"
      },
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "max"
       ],
       "text": "aggregateBy(15m, max)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe - 6 " ],
       "text": "setAlias(MIDe - 6 )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MID6_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "max"
       ],
       "text": "top(10, max)"
      },
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "max"
       ],
       "text": "aggregateBy(15m, max)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe - Uber" ],
       "text": "setAlias(MIDe - Uber)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Quant_MIDUberlandia_central_60min"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/.*/" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "max"
       ],
       "text": "top(10, max)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MID evo" ],
       "text": "setAlias(MID evo)"
      },
      {
       "added": false,
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "max"
       ],
       "text": "aggregateBy(15m, max)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MIDevo_central_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Fila de integração PDE-s",
   "type": "table",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 24 },
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe4" ],
       "text": "setAlias(MIDe4)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Fila_integracao_MIDe4" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe5" ],
       "text": "setAlias(MIDe5)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Fila_integracao_MIDe5" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe6" ],
       "text": "setAlias(MIDe6)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Fila_integracao_MIDe6" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe7" ],
       "text": "setAlias(MIDe7)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Fila_integracao_MIDe7" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 26 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n<h1> \n<b>OUTROS</b></h1></p></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_ContadorOutras_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_Outras_Percent_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 26 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_OUTRAS_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 26 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_OUTRAS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 30 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n<h1> \n<b>TOTAL</b></h1></p></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 30 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_Tudo_Percent_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 30 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_TODAS_5min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 30 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_TODAS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Médio - Hoje",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 34 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Tempo_DIA_GERAL_HOJE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Emitido - Hoje",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quantidade_dia_Total_MID" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Emitido - Tamboré",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quantidade_dia_tambore_MID" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Emitido - MIDe6",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MIDe6_central_DIA" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Emitido - Azure MIDe4",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quantidade_dia_Azure_MIDe4" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Emitido - Azure MIDe5",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quantidade_dia_Azure_MIDe5" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Emitido - Azure MIDe7",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_MIDe7_central_DIA" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Emitido - MIDevo",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Quant_mideevo_central_DIA" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
   "content": "\n\n<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 22px; color: #4682B4;\"><b>Desempenho da Sefaz</b></span>\n\n\n </div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 39 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n<span style=\"font-size: 22px; color: #FFFFFF; \"><b>Autorizador</b> </span></div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 39 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n<span style=\"font-size: 22px; color: #FFFFFF; \"><b>Autorizador Virtual</b> </span></div>"
  },
  {
   "title": "Distribioção do Tempo de Resposta das Secretarias",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 39 },
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "/TempoMedioOnLineMS_sefaz_*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GO",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 41 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_GO" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MT",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 41 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_MT" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "AL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 41 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_AL" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "BA",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 41 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_BA" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DF",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 41 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_DF" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ES",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 44 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_ES" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MA",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 44 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_MA" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PA",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 44 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_PA" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PR",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 45 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_PR" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 45 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_SP" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 47 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_PE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PI",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 47 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_PI" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 47 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_PB" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 49 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_RS" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SRVRS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 49 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_SRVRS" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RJ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 50 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_RJ" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 50 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_RN" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 50 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz_Emissao_periodo" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoMedioOnLineMS_sefaz_SE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}