{
 "title": "REPORT - Analise-MID",
 "tags": [ "DATAS VAREJO" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "content": "<div>\n<p>\n<img src=\"https://uniredeinfo-my.sharepoint.com/personal/hernandes_martins_unirede_net/_layouts/15/guestaccess.aspx?docid=019add617d2da4d48b78a7d349e288209&authkey=ASLOqLFi9YyWYZxXWGNB4_o&e=12e79e2af650446b8d44ab81482a6c7b\" align=\"left\" align=\"top\" height=\"70px\" />\n<h3> <b>Operações</b></h3></p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 0 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size:28px;\">\n\n<p>Última Hora</p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 0 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 28px;\">\n<p>Últimas 2 horas</p></div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "content": "<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 28px;\">\n \n<p>Total Emitido - Hoje</p></div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h2> \n<b>Cupons</b></h2></p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h2> \n<b>% online</b></h2></p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h2> \n<b>Tempo</b></h2></p>\n\n</div>\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 2 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h2> \n<b>Cupons</b></h2></p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 2 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h2> \n<b>% online</b></h2></p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 2 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h2> \n<b>Tempo</b></h2></p>\n\n</div>\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 2 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h2> \n<b>Cupons</b></h2></p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h2> \n<b>% online</b></h2></p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h2> \n<b>Tempo</b></h2></p>\n\n</div>\n"
  },
  { "type": "text", "gridPos": { "h": 1, "w": 4, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 42px;\">\n \n<b>MODA</b></p></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_ContadorMODA_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_MODA_percent_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_MODA_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorMODA_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_MODA_percent_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 4 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_MODA_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorMODA_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_MODA_percent_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "24h" ],
       "text": "average(24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_MODA_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 42px;\">\n\n<b>FOOD</b></p></div>\n"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorFOODSERVICE_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_FOODSERVICE_Percent_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_FOOD_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorFOODSERVICE_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_FOODSERVICE_Percent_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 7 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_FOOD_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorFOODSERVICE_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_FOODSERVICE_Percent_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "24h" ],
       "text": "average(24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_FOOD_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 42px;\">\n<b>POSTOS</b></p></div>\n"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_ContadorPOSTOS_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_POSTOS_percent_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 10 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_POSTOS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorPOSTOS_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_POSTOS_percent_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 10 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_POSTOS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorPOSTOS_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_POSTOS_percent_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "24h" ],
       "text": "average(24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_POSTOS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 42px;\">\n<b>BIG RETAIL</b></p></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 13 },
   "format": "locale",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorBIGRETAIL_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_BIGRETAIL_percent_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 13 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_BIGRETAIL_nova_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 13 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorBIGRETAIL_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_BIGRETAIL_percent_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 13 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_BIGRETAIL_nova_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 13 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorBIGRETAIL_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_BIGRETAIL_percent_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 13 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "24h" ],
       "text": "average(24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_BIGRETAIL_nova_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "content": "\n\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 42px;\">\n<b>OUTROS</b></p></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_ContadorOutras_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_Outras_Percent_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 16 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_OUTRAS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 16 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorOutras_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_Outras_Percent_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 16 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "2h" ],
       "text": "average(2h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_OUTRAS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 16 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorOutras_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_Outras_Percent_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "24h" ],
       "text": "average(24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_OUTRAS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 42px;\">\n<b>TOTAL</b></p></div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 19 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Vertical_Tudo_Percent_nfcedb" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 19 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_TODAS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 19 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_Tudo_Percent_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 19 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_TODAS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 19 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB v3" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_Tudo_Percent_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 19 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MIDe-NFCEDB-VERTICAL" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "24h" ],
       "text": "average(24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "TempoLinx_TODAS_60min" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 22 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 28px;\">\n\n\nComparativo Mesmo Horário (D -1 e D -7) - Última hora</p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 22 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 28px;\">\n\nComparativo Mesmo Horário (D -1 e D -7) - Últimas 2 horas</p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 22 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 28px;\">\n\nComparativo Mesmo Horário (D -1 e D -7) - Acumulado Dia</p>\n\n</div>"
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "D-1" ],
       "text": "setAlias(D-1)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "D-7" ],
       "text": "setAlias(D-7)"
      },
      {
       "added": false,
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "7d" ],
       "text": "timeShift(7d)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Últimas 1 Horas (D-1)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 24 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "D-1" ],
       "text": "setAlias(D-1)"
      },
      {
       "added": false,
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "D-7" ],
       "text": "setAlias(D-7)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "7d" ],
       "text": "timeShift(7d)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Últimas 2 Horas (D-1)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 24 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "D-1" ],
       "text": "setAlias(D-1)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "D-7" ],
       "text": "setAlias(D-7)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "7d" ],
       "text": "timeShift(7d)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Acumulado (D-1)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 24 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Últimas 1 Horas (D-7)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 27 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "7d" ],
       "text": "timeShift(7d)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Últimas 2 Horas (D-7)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 27 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "7d" ],
       "text": "timeShift(7d)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_2h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Acumulado (D-7)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 27 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "7d" ],
       "text": "timeShift(7d)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center;\">\n\n<h3> \n<b>Cupons</b></h3></p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 31 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 28px;\">\n\n<p>Fila de integração PDE-s</p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 4, "y": 31 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 28px;\">\n\n<p>Comparativo Mesmo Horário (Hoje e D-1)</p>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 31 },
   "content": "\n<div style=\"width: 100%; padding: 1px ; text-align: center; font-size: 28px;\">\n\n<p>Comparativo Mesmo Horário (Hoje,D-1, D-7)</p>\n\n</div>"
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 33 },
   "targets": [
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe4" ],
       "text": "setAlias(MIDe4)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Fila_integracao_MIDe4" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe5" ],
       "text": "setAlias(MIDe5)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Fila_integracao_MIDe5" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe6" ],
       "text": "setAlias(MIDe6)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Fila_integracao_MIDe6" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID-PDEs" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "MIDe7" ],
       "text": "setAlias(MIDe7)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Fila_integracao_MIDe7" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total Hoje" ],
       "text": "setAlias(Total Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total D-1" ],
       "text": "setAlias(Total D-1)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Acumulado Hoje",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 33 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total Hoje" ],
       "text": "setAlias(Total Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total D-1" ],
       "text": "setAlias(Total D-1)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Total D-7" ],
       "text": "setAlias(Total D-7)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-7d" ],
       "text": "timeShift(-7d)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Acumulado Hoje",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 33 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Acumulado D-1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 36 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Acumulado D-1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 36 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Acumulado D-7",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 39 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "7d" ],
       "text": "timeShift(7d)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorCuponsTodos_nfcedb_24h"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}