{
 "title": "PRODUTOS-Seller",
 "tags": [ "POSTOS" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div>\n<p>\n<div style=\"width: 100%; height: 100%; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF; \"><img src=\"http://ri.linx.com.br/wp-content/themes/mziq_linx/img/timeline/2015/img-linx.png\" align=\"left\"  height=\"60px\" /></span></div>\n\n\n<center><span style=\"font-size: 36px\" >\n  <b>Seller</b></spam></center>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\r\n<span style=\"font-size: 20px\"><b>DTEF - Transação Financeira</b></span>\r\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 9, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center; padding-top: 5px;\">\r\n<span style=\"font-size: 20px\"><b>MIDe - Emissão de Cupom Fiscal</b></span>\r\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 16px\"><b>GMUD - Pré-Execução</b></span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<span style=\"font-size: 16px\"><b>GMUD - Em Execução</b></span>\n</div>"
  },
  {
   "title": "Quant. Últimos 5min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Qtd5min_Seller" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Últimos 5min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "TempoMsLink REDE" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_total_TML_REDE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Últimos 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "TempoMsLink REDE" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "LNXDBDTEF01_01" },
     "item": { "filter": "Tempo_total_TML_REDE" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quant. Últimos 5min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MID NFCEDB Contador" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": {
      "filter": "Vertical_ContadorPOSTOS_nfcedb_Seller_5min"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Últimos 5min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Tempo-5min-POSTOS_Seller" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo Últimos 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "MID_tempos_Produtos" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "NFCEBD - VM" },
     "item": { "filter": "Tempo-60min-POSTOS_Seller" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "São analisadas as Pre execuções do Dia atual.",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT COUNT(*)\nFROM TRACEGP_HML_DEM_RDM\nWHERE ESTADO_DESCR = 'Pré Execução' and VERTICAL_PRODUTO like '%Seller%' and DATA_INICIO_EXECUCAO = GETDATE()",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Que estão com Status em Execução.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT COUNT(*)\nFROM TRACEGP_HML_DEM_RDM\nWHERE ESTADO_DESCR = 'Em Execução' and VERTICAL_PRODUTO like '%Seller%'",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 },
   "content": "<div>\n\n<center><span style=\"font-size: 22px\" >\n  <b>Geral</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 7 },
   "content": "<div>\n\n<center><span style=\"font-size: 22px\" >\n  <b>Tempo de Resposta</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "content": "<div>\n\n<center><span style=\"font-size: 14px\" >\n  <b>Serviço</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "content": "<div>\n\n<center><span style=\"font-size: 18px\" >\n  <b>Qtd Acesso</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
   "content": "<div>\n\n<center><span style=\"font-size: 18px\" >\n  <b>Tempo</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 9 },
   "content": "<div>\n\n<center><span style=\"font-size: 14px\" >\n  <b>Evolução de Tempo e Quantidade de acesso a funcionalidade</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 9 },
   "content": "<div>\n\n<center><span style=\"font-size: 18px\" >\n  <b>Clientes</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 9 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 22px;\" >\n  <b>Login</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 9 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 14px\" >\n  <b>Consulta Vendas</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 9 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 12px\" >\n  <b>Lançamento de Vendas</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>LMC</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "content": "<div style=\"width: 100%; height: 100%; padding-top:35px; text-align: center;\">\n\n<center><span style=\"font-size: 24px;\" >\n  <b>Login</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Tempo Funcionalidade 0 - Todos" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "QTD_Fun_0_Todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Tempo Funcionalidade 0 - Todos" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "Tempo_Fun_0_Todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "Tempo" }
   ],
   "targets": [
    {
     "application": { "filter": "Tempo Funcionalidade 0 - Todos" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Tempo" ],
       "text": "setAlias(Tempo)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "Tempo_Fun_0_Todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Tempo Funcionalidade 0 - Todos" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Quantidade" ],
       "text": "setAlias(Quantidade)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "QTD_Fun_0_Todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 11 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 22px;\" >\n  <b>Rede Campeao</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_0_SELLERWEB_REDECAMPEAO" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_16105_SELLERWEB_REDECAMPEAO"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_16810_SELLERWEB_REDECAMPEAO"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_17110_SELLERWEB_REDECAMPEAO"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 13 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 22px;\" >\n  <b>Cidade Jardim</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_0_SELLERWEB_CIDADEJARDIM" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_16105_SELLERWEB_CIDADEJARDIM"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_16810_SELLERWEB_CIDADEJARDIM"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_17110_SELLERWEB_CIDADEJARDIM"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "content": "<div style=\"width: 100%; height: 100%; padding-top:10px; text-align: center;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Consultar Vendas</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Tempo Funcionalidade 16105 - Todos"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "QTD_Fun_16105_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Tempo Funcionalidade 16105 - Todos"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "Tempo_Fun_16105_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "s", "label": "Tempo" }
   ],
   "targets": [
    {
     "application": {
      "filter": "Tempo Funcionalidade 16105 - Todos"
     },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Tempo" ],
       "text": "setAlias(Tempo)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "Tempo_Fun_16105_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": {
      "filter": "Tempo Funcionalidade 16105 - Todos"
     },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Quantidade" ],
       "text": "setAlias(Quantidade)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "QTD_Fun_16105_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 15 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 22px;\" >\n  <b>Auto Posto Flanboyant</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_0_SELLERWEB_AUTOPOSTOFLANB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_16105_SELLERWEB_AUTOPOSTOFLANB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_16810_SELLERWEB_AUTOPOSTOFLANB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_17110_SELLERWEB_AUTOPOSTOFLANB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 17 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 22px;\" >\n  <b>Cardeal</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 17 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_0_SELLERWEB_CARDEAL" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 17 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_16105_SELLERWEB_CARDEAL" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 17 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_16810_SELLERWEB_CARDEAL" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 17 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_17110_SELLERWEB_CARDEAL" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 19 },
   "content": "<div style=\"width: 100%; height: 100%; padding-top:15px; text-align: center;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Lançamento de Vendas</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "TEMPO Funcionalidade 16810 - Todos"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "QTD_Fun_16810_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "TEMPO Funcionalidade 16810 - Todos"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "Tempo_Fun_16810_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "s", "label": "Tempo" }
   ],
   "targets": [
    {
     "application": {
      "filter": "TEMPO Funcionalidade 16810 - Todos"
     },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Tempo" ],
       "text": "setAlias(Tempo)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "Tempo_Fun_16810_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": {
      "filter": "TEMPO Funcionalidade 16810 - Todos"
     },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Quantidade" ],
       "text": "setAlias(Quantidade)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "QTD_Fun_16810_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 19 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 22px;\" >\n  <b>Digos</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_0_SELLERWEB_DIGOS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_16105_SELLERWEB_DIGOS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_16810_SELLERWEB_DIGOS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_17110_SELLERWEB_DIGOS" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 21 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 22px;\" >\n  <b>APMW</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_0_SELLERWEB_APMW" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_16105_SELLERWEB_APMW" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_16810_SELLERWEB_APMW" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_17110_SELLERWEB_APMW" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 23 },
   "content": "<div style=\"width: 100%; height: 100%; padding-top:15px; text-align: center;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Livro de Movimentação de Caixa</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "TEMPO Funcionalidade 17110 - Todos"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "QTD_Fun_17110_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 23 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "TEMPO Funcionalidade 17110 - Todos"
     },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "Tempo_Fun_17110_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "s", "label": "Tempo" }
   ],
   "targets": [
    {
     "application": {
      "filter": "TEMPO Funcionalidade 17110 - Todos"
     },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Tempo" ],
       "text": "setAlias(Tempo)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "Tempo_Fun_17110_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": {
      "filter": "TEMPO Funcionalidade 17110 - Todos"
     },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Quantidade" ],
       "text": "setAlias(Quantidade)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "QTD_Fun_17110_todos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 23 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 22px;\" >\n  <b>Rede Florense</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 23 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_0_SELLERWEB_REDEFLORENSE" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 23 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_16105_SELLERWEB_REDEFLORENSE"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 23 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_16810_SELLERWEB_REDEFLORENSE"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 23 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_17110_SELLERWEB_REDEFLORENSE"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 25 },
   "content": "<div style=\"width: 100%; height: 100%; text-align: center;\">\n\n<center><span style=\"font-size: 22px;\" >\n  <b>Novo Horizonte</b></spam></center>\n</div>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 25 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": { "filter": "func_0_SELLERWEB_NOVOHORIZONTE" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 25 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_16105_SELLERWEB_NOVOHORIZONTE"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 25 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_16810_SELLERWEB_NOVOHORIZONTE"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 25 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Metricas_clientes" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "kpi_seller" },
     "item": {
      "filter": "func_17110_SELLERWEB_NOVOHORIZONTE"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}