{
 "title": "CORPORATIVO - Storage-Tambore Modelo Novo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n\n<div style=\"width: 100%; height: 100%;\">\n<img src=\"http://ri.linx.com.br/wp-content/themes/mziq_linx/img/timeline/2015/img-linx.png\" align=\"left\"  height=\"70px\" wieght=\"50px\" /> \n<span style=\"font-size: 28px; padding-left:50px;\" >\n  <b>Storage</b></spam>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Top - 5 Uso de Discos</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 3 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Top 5 - Uso de Memoria Laminas</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 3 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Espaço usado em Percentil - VMFS - TOP10</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 3 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Espaço usado em Percentil - VMFS - TOP10</b></spam></center>\n</div>"
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "application": { "filter": "Disk partitions" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "avg"
       ],
       "text": "top(5, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/Lamina DELL - ESXI.*/" },
     "item": { "filter": "/Used disk on VMFS.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 5 },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "avg"
       ],
       "text": "top(5, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/Lamina UCS Blade-DC.*/" },
     "item": { "filter": "/Memory Used.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Espaço usado em Percentil - VMFS",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 5 },
   "targets": [
    {
     "application": { "filter": "Disk partitions" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "avg"
       ],
       "text": "top(10, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/Lamina DELL - ESXI.*/" },
     "item": { "filter": "/Used Space % on VMFS.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Espaço livre - VMFS",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "application": { "filter": "Disk partitions" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "avg"
       ],
       "text": "top(10, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/Lamina DELL - ESXI.*/" },
     "item": { "filter": "/Free Space on VMFS.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 12 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Uso de Memoria por Lamina</b></spam></center>\n</div>"
  },
  {
   "title": "Used Memory % - Lamina UCS Blade-DC11",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent", "label": "Memoria Usada" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/Lamina UCS Blade-DC/" },
     "item": { "filter": "Used Memory %" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 15 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Espaço livre - VMFS</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 15 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Espaço livre - VMFS</b></spam></center>\n</div>"
  },
  {
   "title": "Status - VMFS",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 17 },
   "targets": [
    {
     "application": { "filter": "Virtual Machines" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/Lamina DELL - ESXI.*/" },
     "item": { "filter": "/VM Guest State.*/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "OS Identificado Instalado - VMFS",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 17 },
   "targets": [
    {
     "application": { "filter": "Virtual Machines" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/Lamina DELL - ESXI.*/" },
     "item": { "filter": "/VM Guest OS.*/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 24 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Status - Laminas</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 24 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Status Blade</b></spam></center>\n</div>"
  },
  {
   "title": "Lamina UCS Blade-DC1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC1" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC9",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC9" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC16",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC16" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI33",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXi33" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 26 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Overall System Status</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 26 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Temprature Status</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 26 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Power Status</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 26 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Health Status</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 26 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Voltagem de entrada | Ampere de entrada</b></spam></center>\n</div>"
  },
  {
   "title": "Lamina UCS Blade-DC2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC2" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC10",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC10" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI27",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXI27" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI34",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXI34" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "Overall System Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "Overall Temprature Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC Power Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC Health Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Voltagem de entrada",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "6",
        "avg"
       ],
       "text": "top(6, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": {
      "filter": "/Power Supply.*..Input Voltage/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC3",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC3" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC11",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC11" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI28",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXI28" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI35",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXI35" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 31 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>FAN Status</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 31 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>IOM Subsys Status</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 31 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>iKVM  Health Status</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 31 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Redundancy Status</b></spam></center>\n</div>"
  },
  {
   "title": "Lamina UCS Blade-DC4",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC4" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC12",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC12" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI29",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXI29" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI36",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXI36" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "avg"
       ],
       "text": "groupBy(15m, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC Fan Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "15m",
        "avg"
       ],
       "text": "groupBy(15m, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "IOM Subsystem Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "iKVM Subsystem Health Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Chassis Status" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC Redundancy Status" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC5",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC5" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC13",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC13" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI30",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXi30" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI37",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXI37" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 34 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Status Blade</b></spam></center>\n</div>"
  },
  {
   "title": "Ampere de entrada",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "6",
        "avg"
       ],
       "text": "top(6, avg)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "/Power Supply.*.Input Amps/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC6",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC6" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC14",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC14" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI31",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXI31" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI38",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXI38" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 36 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Temperatura CPU</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 36 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Temperatura Chassis</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 36 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>Consumo de Energia</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 36 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 18px\" >\n  <b>System Input Power</b></spam></center>\n</div>"
  },
  {
   "title": "Lamina UCS Blade-DC8",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC8" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina UCS Blade-DC15",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina UCS Blade-DC15" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lamina DELL - ESXI32",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Lamina DELL - ESXi32" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 38 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC CPU Temprature" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 38 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "Chassis FrontPanel Temprature" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 38 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC System Energy Consumption" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 38 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Modulo de Fibra - Matriz" },
     "item": { "filter": "CMC System Input Power" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}