{
 "title": "CORP - Infra-DATABASES",
 "description": "Displays metrics collected by the host Zabbix Server",
 "tags": [
  "Infraestrutura",
  "Banco de Dados"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "host", "label": "Servidores", "query": "*.*" }
  ]
 },
 "panels": [
  {
   "title": "Alarmes",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": {
    "WebMonitorPRD": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "tags": { "filter": "" },
     "trigger": { "filter": "/.*/" }
    }
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "content": "<div style=\"width: 100%; height: 100%; background-color:rgb(128,128,128); padding:1px; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF; \"><b> Sistema Operacional</b> </span></div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<spam style=\"font-size: 24px;\">\n<b>CPU</b>\n</spam>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 6 },
   "content": "<div style=\"width: 100%; text-align: center;\">\n<spam style=\"font-size: 24px;\">\n<b>DRIVER</b>\n</spam>\n</div>"
  },
  {
   "title": "Total de uso de CPU em % - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total de uso de CPU em %" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total de uso de CPU em %" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Indicadores - Disco Unidades",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Free disk.*(percentage)/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used disk space on C: - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Used disk space on C:" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Used disk space on C:" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Avg. Disk Queue Length - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Drives - Unidades" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Avg. Disk Queue Length" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Drives - Unidades" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Avg. Disk Queue Length" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "% Idle Time - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Drives - Unidades" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "% Idle Time" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Drives - Unidades" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "% Idle Time" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Processor Queue Lengh - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "/CPU*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Processor Queue Lengh" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/CPU*/" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Processor Queue Lengh" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Avg.Disk sec_Write - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Drives - Unidades" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Avg.Disk sec_Write" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Drives - Unidades" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Avg.Disk sec_Write" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Disk space percentage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Free disk.*(percentage)/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "File write bytes per second - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "File write bytes per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "File write bytes per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "File read bytes per second - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "File read bytes per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "File read bytes per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Load Average Total - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Load Average Total" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Load Average Total" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Average disk write queue length - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Average disk write queue length"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Average disk write queue length"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Avg.Disk sec_Read - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Drives - Unidades" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Avg.Disk sec_Read" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Drives - Unidades" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Avg.Disk sec_Read" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Average disk read queue length - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Average disk read queue length" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "Average disk read queue length" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "content": "\n<div style=\"width: 100%; height: 100%; background-color:rgb(128,128,128); padding:1px; text-align: center;\">\n<span style=\"font-size: 24px; color: #FFFFFF; \"><b>SQL</b> </span></div>"
  },
  {
   "title": "Number Users Connected - Atual e ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Number Users Connected/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Number Users Connected/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Transactions per second - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Transactions per second/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Transactions per second/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Page Life Expectancy  -  Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Page Life Expectancy/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Page Life Expectancy/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Lock Waits per second - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Lock Waits per second/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Lock Waits per second/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Blocked Processes - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Blocked Processes/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Blocked Processes/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Target Server Memory (KB) - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Target Server Memory.*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Target Server Memory.*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Batch Requests/sec - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Batch Requests/sec/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Batch Requests/sec/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SQL Compilations/sec - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*SQL Compilations/sec/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*SQL Compilations/sec/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Buffer Cash Hit Ratio - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Buffer Cash Hit Ratio/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Buffer Cash Hit Ratio/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Locks Requests/sec - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Locks Requests/sec/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Locks Requests/sec/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of Deadlocks per second - Atual e Ontem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Number of Deadlocks per second/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Number of Deadlocks per second/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Log File Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Log File Size/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Log File Size/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Checkpoint pages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Checkpoint pages/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Checkpoint pages/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Server Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Total Server Memory/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Total Server Memory/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Data File Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Data File Size/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Data File Size/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Full Scans",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Full Scans/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Full Scans/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Page Splits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Page Splits/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*Page Splits/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Default Instance: Memory Grants Pending",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Hoje" ],
       "text": "setAlias(Hoje)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Default Instance: Memory Grants Pending/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/SQL*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ontem" ],
       "text": "setAlias(Ontem)"
      },
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/.*Default Instance: Memory Grants Pending/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}