{
 "title": "Redes_todos_devices",
 "description": "Displays metrics collected by the host Zabbix Server",
 "tags": [ "Corporativo" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "base", "query": "Suporte_Grupo/Grupo-Soma.*" },
   {
    "name": "Grupo",
    "label": "Grupo",
    "query": "HG000000000038/AM/Manaus/Rede, HG000000000038/MG/Belo Horizonte/Rede, HG000000000038/MG/Uberlandia/Rede, HG000000000038/PE/Recife/Rede, HG000000000038/PR/Cascavel/Rede, HG000000000038/RJ/Rio de Janeiro/Rede, HG000000000038/RS/Porto Alegre/Rede, HG000000000038/SC/Blumenau/Rede, HG000000000038/SC/Florianopolis/Rede, HG000000000038/SC/Joinvile/Rede, HG000000000038/SP/Bauru/Rede, HG000000000038/SP/Bebedouro/Rede, HG000000000038/SP/Campinas/Rede, HG000000000038/SP/Matriz/Rede, HG000000000038/SP/Pinheiros/Rede"
   },
   { "name": "host", "label": "Devices", "query": "$Grupo.*" },
   { "name": "Interface", "label": "Interface - Incoming", "query": "$Grupo.$host.Interface(s).*" },
   { "name": "Interface2", "label": "Interface - Outgoing", "query": "$Grupo.$host.Interface(s).*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n\n<div style=\"width: 100%; height: 100%;\">\n<img src=\"http://ri.linx.com.br/wp-content/themes/mziq_linx/img/timeline/2015/img-linx.png\" align=\"left\"  height=\"70px\" wieght=\"50px\" /> \n<span style=\"font-size: 28px; padding-left:10px;\" >\n  <b>Corp. Redes</b></spam>\n<span style=\"font-size: 24px; color: #FFFFFF; float:right; padding-right: 20px;\"><img src=\"#\" align=\"center\"  height=\"80px\" /></span>\n\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 3 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Alarmes Ativos</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 7, "y": 3 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Alarmes em Tratativa</b></spam></center>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 3 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Status do Link de Internet</b></spam></center>\n</div>"
  },
  {
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "targets": {
    "0": {},
    "Coletores Linx": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "Conec_Zabbix": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "WebMonitorPRD": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 5 },
   "targets": {
    "0": {},
    "Coletores Linx": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Suporte_Grupo" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "INFRAESTRUCTURE:Conectividade" },
     "trigger": { "filter": "" }
    },
    "Conec_Zabbix": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/Suporte_Grupo/Grupo-Soma.*/" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "WebMonitorPRD": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "/.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "type": "table",
   "description": "Status 1 = ok\nStatus 0 = Falha",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(: ICMP.*)/",
        " "
       ],
       "text": "replaceAlias(/(: ICMP.*)/,  )"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(Kinoplex - )/",
        " "
       ],
       "text": "replaceAlias(/(Kinoplex - )/,  )"
      }
     ],
     "group": { "filter": "$Grupo" },
     "host": { "filter": "/Link/" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming traffic on interface - Todas as Portas",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "/IN/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing traffic on interface - Todas as Portas",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 12 },
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Out/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 12 },
   "content": "<div style=\"padding-top:0px;\">\n\n<center><span style=\"font-size: 24px\" >\n  <b>Métricas Device - Últimas 6 horas</b></spam></center>\n</div>"
  },
  {
   "title": "Gráfico de Evolução Interface - Incoming Selecionada Hoje e Ontem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "decbytes", "label": "Uso da Interface" }
   ],
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "$Interface" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interface(s)" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "$Interface" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso de CPU no Device Selecionado.",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 22 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "System CPU Usage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso de Memoria no Device Selecionado.",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 22 },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "System Memory Usage(%)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Perda de Pacotes - Link",
   "type": "table",
   "description": "Verificado através do percentual de perda de pacotes do ICMP com o Coletor da Filial.",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 22 },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(: ICMP.*)/",
        " "
       ],
       "text": "replaceAlias(/(: ICMP.*)/,  )"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(Kinoplex - )/",
        " "
       ],
       "text": "replaceAlias(/(Kinoplex - )/,  )"
      }
     ],
     "group": { "filter": "$Grupo" },
     "host": { "filter": "/Link/" },
     "item": { "filter": "ICMP Perda Pacotes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gráfico de Evolução Interface - Outgoing Selecionada Hoje e Ontem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "decbytes", "label": "Uso da Interface" }
   ],
   "targets": [
    {
     "application": { "filter": "Interface(s)" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$host" },
     "item": { "filter": "$Interface2" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interface(s)" },
     "functions": [
      {
       "def": {
        "category": "Time",
        "defaultParams": [ "24h" ],
        "name": "timeShift",
        "params": [
         {
          "name": "interval",
          "options": [
           "24h",
           "7d",
           "1M",
           "+24h",
           "-24h"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "-24h" ],
       "text": "timeShift(-24h)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "$Interface2" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}